"""Live socket integration smoke test connecting Backend to live ML service on port 8001."""
import asyncio
import os
import sys

# Ensure backend app is in pythonpath
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from starlette.testclient import TestClient
from app.core.config import get_settings
from app.integrations.ml.http_provider import HttpMLProvider
from app.integrations.ml.provider import StubMLProvider, get_ml_provider
from app.main import app as backend_app


async def run_live_smoke():
    print("=== JalRakshak AI Live Backend -> ML Smoke Test ===")
    print("Connecting to ML service at http://127.0.0.1:8001...")

    provider = HttpMLProvider(
        base_url="http://127.0.0.1:8001",
        auth_token="dev-ml-token",
        timeout_seconds=5.0,
        fallback_stub=StubMLProvider(),
    )

    # 1. Test live Nowcast Manifest via HTTP
    print("\n[1/5] Testing POST /internal/ml/nowcast over live HTTP...")
    nowcast = await provider.get_nowcast_manifest()
    assert nowcast["model_version"] == "pysteps-lk-v1", f"Unexpected model version: {nowcast}"
    assert nowcast["units"] == "mm/h", f"Unexpected units: {nowcast.get('units')}"
    assert len(nowcast["bounds"]) == 4, f"Invalid bounds: {nowcast.get('bounds')}"
    assert "quality_score" in nowcast and "confidence" in nowcast, "Missing QC / confidence separation"
    print(f" -> SUCCESS: Nowcast Manifest generated by {nowcast['model_version']}")
    print(f"    COG URL: {nowcast['cog_url']}")
    print(f"    Quality Score: {nowcast['quality_score']}, Model Confidence: {nowcast['confidence']}")

    # 2. Test live Inundation Manifest via HTTP
    print("\n[2/5] Testing POST /internal/ml/inundation over live HTTP...")
    inundation = await provider.get_inundation_manifest()
    assert inundation["model_version"] == "hydro-susceptibility-v1"
    assert inundation["is_physically_calibrated"] is False, "Physical calibration safety flag violated"
    assert inundation.get("max_depth_meters") is None, "Fabricated physical depth in meters was not removed"
    assert "depth_cog_url" in inundation
    print(f" -> SUCCESS: Inundation Manifest generated by {inundation['model_version']}")
    print(f"    Depth COG: {inundation['depth_cog_url']}")
    print(f"    Physically Calibrated: {inundation['is_physically_calibrated']} (Scientific Safety Preserved)")

    # 3. Test live Risk Cells via HTTP
    print("\n[3/5] Testing POST /internal/ml/risk-assessment over live HTTP...")
    cells = await provider.get_risk_cells()
    assert isinstance(cells, list) and len(cells) > 0, "No cells returned"
    first = cells[0]
    assert len(first["h3_cell_id"]) == 15, f"Invalid H3 index: {first['h3_cell_id']}"
    assert first["risk_level"] in ["LOW", "MODERATE", "HIGH", "SEVERE"]
    assert first.get("flood_depth_m") is None, "Unsupported physical water depth was not null"
    print(f" -> SUCCESS: Retrieved {len(cells)} scored H3 cells")
    print(f"    Sample cell: H3={first['h3_cell_id']} Ward={first.get('ward_id')} Risk={first['risk_level']}")

    # 4. Test live Citizen Report Verification via HTTP
    print("\n[4/5] Testing POST /internal/ml/verify-report over live HTTP...")
    verif = await provider.verify_report(
        report_id="rep-live-test-01",
        image_url="http://localhost:9000/jalrakshak/reports/test.jpg",
        description="High water level on LBS Marg Kurla west, traffic blocked",
    )
    assert verif["verification_status"] == "AI_VERIFIED"
    assert verif.get("verification_state") == "HEURISTIC"
    assert verif.get("detected_water_level_cm") is None, "Fabricated 75cm water depth was not removed"
    assert verif["is_flood_related"] is True
    print(f" -> SUCCESS: Report verified with status {verif['verification_status']} (State: {verif.get('verification_state')})")
    print(f"    Calibrated: {verif.get('is_calibrated')}, Detected Water Depth: {verif.get('detected_water_level_cm')}")

    # 5. Test Backend Public API wired to live ML Provider
    print("\n[5/5] Testing Backend Public REST API with live ML Provider...")
    backend_app.dependency_overrides[get_ml_provider] = lambda: provider
    client = TestClient(backend_app)
    try:
        res_nowcast = client.get("/api/v1/nowcast/manifest")
        assert res_nowcast.status_code == 200
        assert res_nowcast.json()["model_version"] == "pysteps-lk-v1"

        res_risk = client.get("/api/v1/risk/cells")
        assert res_risk.status_code == 200
        assert res_risk.json()["total"] == len(cells)
        print(" -> SUCCESS: Public endpoints (/api/v1/nowcast/manifest, /api/v1/risk/cells) verified!")
    finally:
        backend_app.dependency_overrides.clear()

    print("\n=======================================================")
    print("ALL LIVE INTEGRATION SMOKE TESTS PASSED SUCCESSFULLY!")
    print("=======================================================")


if __name__ == "__main__":
    asyncio.run(run_live_smoke())
